### ISSUE TITLE
[Deliverable 3] lofi Prototype

### ISSUE THREAD

**Issue by cbondurant** [Berea-CS-Courses/capstone-project-cbondurant#7]
Writeup of prototyping efforts

**Comment by jazzij** [comment]
Thoughts from report out: Consider adding a "stroke config" menu along with Tool Config to allow the individual stroke editing that you want. Here's a little bit how its implemented in Adobe Illustrator (https://www.youtube.com/watch?v=PPBQYUyeX68) (you can see tool menu down the left and stroke options across the top)

**Comment by walkerje** [comment]
Great initial sketch of the overarching GUI system users will interact with. A user interaction diagram would have been effective to show the order of steps a user would need to follow, and a data flow diagram would likely have been effective when thinking about how tools interoperate with the rest of your systems. Paired with your list of verbs, what your project will ultimately do is well described, but how all this functionality fits together needs elaboration. **I strongly suggest "zooming out" from a focus on functionality to focus more on the project's presentation and user interaction.**

Extra suggestion: Getting familiar with QT's "Dock" widget might similarly make it easier to deliberate presentation due to how flexible they are. Scribus, an open-source desktop publishing softwarez, might be a good source of inspiration for this.
